config/routes.rb
Rails.application.routes.draw do

root to: 'cocktails#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [ :index, :show, :new, :create ] do
    resources :doses, only: [ :new, :create]
  end
  resources :doses, only: [ :destroy ]

  # namespace :admin do
  #   resources :cocktails, only: [ :update, :edit, :destroy ]
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses

  validates :name, uniqueness: true, presence: true

  mount_uploader :photo, PhotoUploader
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses

  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [ :show ]

  def index
    @cocktails = Cocktail.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def show
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, except: [ :destroy ]

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
 <%= render "shared/banner" %>
 <div class="container text-center">

  <div class="row">
    <% @cocktails.each do |cocktail| %>
    <%= render "shared/card", cocktail: cocktail %>
    <% end %>
  </div>
  <br>
  <%= link_to "Add cocktails..", new_cocktail_path(@cocktail), class: "btn btn-primary"%>

</div>

app/views/cocktails/new.html.erb
<div class="container">
  <h1>Add your cocktail</h1>

  <%= simple_form_for @cocktail do |f| -%>
    <%= f.input :name %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit class: "btn btn-success"%>
  <% end -%>

  <br>
  <%=  link_to "Back to Cocktails", cocktails_path%>
</div>

app/views/cocktails/show.html.erb
<!-- <div class="wrapper goood"> -->
<div class="container">

<!--   <div class="your-cocktail"> -->
    <h1> <%= @cocktail.name %></h1>
    <%= link_to "Add a dose", new_cocktail_dose_path(@cocktail) %>

    <br>
    <br>
    <div class="container">
      <ul>
        <% @cocktail.doses.each do |dose| %>
        <li>
          <%= dose.description %> of <%= dose.ingredient.name %>
          <%= link_to "Delete", dose_path(dose),
          method: :delete,
          data: { confirm: "Are you sure?" } %>
        </li>
        <% end %>
      </ul>
      <br>
      <%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>

    </div>
    <%= link_to "Back to Cocktails", cocktails_path %>
<!--   </div> -->
</div>
<!-- </div>
 -->

app/views/doses/new.html.erb
<div class="container">

  <%= simple_form_for [@cocktail, @dose] do |f| -%>
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.submit class: "btn btn-warning"%>
  <% end %>

  <br>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>

  </body>
</html>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(76,156,72,-114.4) 0%, rgba(41,30,97,9.6) 161%), url('<%= cl_image_path "good-morning-vietnam.jpg" %> ');">
  <div class="banner-content">
    <h1>Goooood morning Cocktails</h1>
    <p>Make your own drink</p>
    <a class="btn btn-warning btn-lg">Add cocktail</a>
  </div>
</div>

app/views/shared/_card.html.erb
<%= link_to cocktail_path(cocktail) do %>
  <div class="col-xs-12 col-sm-4">
    <% url = cocktail.photo.blank? ? image_path("cocktail_placeholder.jpg") : cl_image_path(cocktail.photo, height: 300, width: 400) %>
    <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= url %>')">

      <div class="card-description">
        <h2><%= cocktail.name.capitalize %></h2>
        <p><% cocktail.doses.each do |dose| %>
          <%= "#{dose.description} of #{dose.ingredient.name}" %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
<% end  %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="navbar-element">
    <ul class="menu-list">
      <li><%= link_to "home", root_path %></li>
      <li><%= link_to "Add Cocktail", new_cocktail_path(@cocktail) %></li>
    </ul>
  </div>
</div>


<!--  <div class="logo"> -->
<!-- </div> -->